Repository Maathru/Frontend-Web-, pull requests merged in 2024-09, with the labels that each got.

#108 Parent clinics to dashboard
  src/components/Calendar.jsx
  src/components/userComponents/ParentClincsSection.jsx
  src/pages/user/dashboard.jsx
  src/service/clinicService.js
Labels: documentation

#109 Midwife dashboard content and shardcn calendar to old calendar
  src/components/Calendar.jsx
  src/components/userComponents/ParentClincsSection.jsx
  src/pages/admin/adminDashboard.jsx
  src/pages/admin/manageClinics.jsx
  src/pages/midwife/dashboard.jsx
  src/service/clinicService.js
  src/service/employeeService.js
  src/service/userService.js
Labels: documentation

#110 Paginations to tab based system
  src/App.jsx
  src/components/BasicTabs.jsx
  src/components/EligibleComponents/DiseasesDetails.jsx
  src/components/EligibleComponents/FamilyHealthDetails.jsx
  src/components/EligibleComponents/FamilyNutrition.jsx
  src/components/EligibleComponents/FilledByMOHDoctor.jsx
  src/components/EligibleComponents/FilledByMidwife.jsx
  src/components/EligibleComponents/ForBoth.jsx
  src/components/EligibleComponents/Habits.jsx
  src/components/EligibleComponents/HealthDetails.jsx
  src/components/EligibleComponents/HomeAndWorkplace.jsx
  src/components/EligibleComponents/MainDetails.jsx
  src/components/EligibleComponents/OtherDetails.jsx
  src/components/EligibleComponents/SpeciallyForWoman.jsx
  src/config/navConfig.js
  src/data/eligibleData.js
  src/pages/user/eligible.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible3.jsx
  src/pages/user/eligible5.jsx
Labels: documentation

#113 Pregnancy card to tab system
  src/App.jsx
  src/components/PregnancyComponents/ClinicalConservation.jsx
  src/components/PregnancyComponents/CurrentPregnancyStatus.jsx
  src/components/PregnancyComponents/FamilyHistoryDetails.jsx
  src/components/PregnancyComponents/HealthDetails.jsx
  src/components/PregnancyComponents/MainDetails.jsx
  src/components/PregnancyComponents/MarkAttendance.jsx
  src/components/PregnancyComponents/ParentsDetails.jsx
  src/components/PregnancyComponents/PostnatalCare.jsx
  src/components/PregnancyComponents/PregnancyHistory.jsx
  src/components/PregnancyComponents/PrenatalCareRelated.jsx
  src/components/userComponents/dateInput.jsx
  src/components/userComponents/fourInputs.jsx
  src/components/userComponents/singleInput.jsx
  src/config/navConfig.js
  src/data/pregnancyData.js
  src/pages/pregnancycard/pregnancy.jsx
  src/pages/pregnancycard/pregnancy1.jsx
  src/pages/pregnancycard/pregnancy2.jsx
  src/pages/pregnancycard/pregnancy3.jsx
  src/pages/pregnancycard/pregnancy4.jsx
Labels: documentation

#114 Update .gitignore
  .gitignore
Labels: enhancement

#116 Pregnancy child
  src/components/PregnancyComponents/AddRecordForm.jsx
  src/components/PregnancyComponents/ChildBirth.jsx
  src/components/PregnancyComponents/ClinicalConservation.jsx
  src/data/pregnancyData.js
  src/pages/pregnancycard/pregnancy.jsx
Labels: functionality implemented

#115 fixed tabs styles
  .env
  src/components/EligibleComponents/FamilyHealthDetails.jsx
  src/components/EligibleComponents/HealthDetails.jsx
  src/components/EligibleComponents/OtherDetails.jsx
  src/pages/user/eligible.jsx
Labels: CSS Fixings

#118 Other details to textarea
  src/components/EligibleComponents/FamilyNutrition.jsx
  src/components/EligibleComponents/ForBoth.jsx
  src/components/EligibleComponents/HomeAndWorkplace.jsx
  src/components/PregnancyComponents/ChildBirth.jsx
  src/components/userComponents/boolTextInput.jsx
  src/components/userComponents/eligibleCardBoolInput.jsx
  src/components/userComponents/minHeightTextarea.jsx
  src/components/userComponents/speciallyWomenInput.jsx
Labels: documentation
