Repository Maathru/Frontend-Web-, pull requests merged in 2024-07, with the labels that each got.

#23 Forum UI
  .env
  package-lock.json
  package.json
  src/App.jsx
  src/components/ui/item.jsx
  src/pages/answer.jsx
  src/pages/forum.jsx
  src/pages/question.jsx
  vite.config.js
  yarn.lock
Labels: documentation

#24 Clinic
  package.json
  public/locales/en/clinic.json
  public/locales/en/clinicDates.json
  public/locales/en/clinicReports.json
  public/locales/en/drug.json
  public/locales/en/drugAdd.json
  public/locales/en/viewClinics.json
  public/locales/sin/clinic.json
  public/locales/sin/clinicReports.json
  public/locales/sin/drug.json
  public/locales/sin/drugAdd.json
  public/locales/sin/viewClinics.json
  src/App.jsx
  src/components/ui/button.jsx
  src/components/ui/calendar.jsx
  src/pages/clinic.jsx
  src/pages/doctor/clinic.jsx
  src/pages/doctor/clinicDates.jsx
  src/pages/doctor/clinicReports.jsx
  src/pages/doctor/viewClinics.jsx
  src/pages/drug.jsx
  src/pages/drugAdd.jsx
  yarn.lock
Labels: enhancement

#25 child growth page
  package.json
  public/locales/en/growth.json
  src/App.css
  src/App.jsx
  src/assets/user/salmon-eggs.png
  src/assets/user/tofu.png
  src/assets/user/walking.png
  src/components/footer.jsx
  src/pages/doctor/clinicReports.jsx
  src/pages/landing.jsx
  src/pages/user/growth.jsx
  tailwind.config.js
  yarn.lock
Labels: enhancement

#26 Auth basics
  jsconfig.json
  package-lock.json
  package.json
  src/App.jsx
  src/components/navbar.jsx
  src/components/toast.js
  src/components/ui/alert-dialog.jsx
  src/components/ui/button.jsx
  src/context/userAuth.jsx
  src/main.jsx
  src/pages/doctor/clinicReports.jsx
  src/pages/landing.jsx
  src/pages/login.jsx
  src/pages/notFound.jsx
  src/pages/signup.jsx
  src/pages/user/dashboard.jsx
  src/service/userService.js
  yarn.lock
Labels: documentation

#27 Sign up/in error visualizing
  src/pages/login.jsx
  src/pages/signup.jsx
  src/service/userService.js
Labels: enhancement

#29 fixed login error styles
  src/index.css
  src/pages/login.jsx
  src/pages/signup.jsx
  tailwind.config.js
Labels: enhancement

#30 Calendar component
  src/components/DateCalendarServerRequest.jsx
  src/pages/user/dashboard.jsx
Labels: invalid

#33 Write block error fixed
  package.json
  src/App.jsx
  yarn.lock
Labels: documentation

#35 Dashboard and Forum
  .env
  public/locales/en/eligibleDashboard.json
  src/App.jsx
  src/assets/user/clinic.png
  src/assets/user/dashboardImage-eligible.png
  src/assets/user/dashboardImage-user.png
  src/assets/user/memory.png
  src/assets/user/midwife.png
  src/components/DateCalendarServerRequest.jsx
  src/components/ScrollToTop.jsx
  src/components/footer.jsx
  src/components/navbar.jsx
  src/components/ui/button.jsx
  src/components/ui/item.jsx
  src/components/userComponents/eligibleCardBoolInput.jsx
  src/components/userComponents/wrapperCard.jsx
  src/index.css
  src/pages/answer.jsx
  src/pages/blog/blog.jsx
  src/pages/doctor/clinic.jsx
  src/pages/doctor/clinicDates.jsx
  src/pages/doctor/viewClinics.jsx
  src/pages/drug.jsx
  src/pages/forum.jsx
  src/pages/landing.jsx
  src/pages/login.jsx
  src/pages/question.jsx
  src/pages/signup.jsx
  src/pages/user/dashboard.jsx
  src/pages/user/eligible1.jsx
  src/service/answerService.js
  src/service/axiosInstance.js
  src/service/forumService.js
  src/service/userService.js
Labels: documentation

#36 added more input field into drugAdd
  public/locales/en/drugAdd.json
  public/locales/sin/drugAdd.json
  src/pages/drug.jsx
  src/pages/drugAdd.jsx
  src/service/drugService.js
Labels: enhancement

#38 Eligible forms dynamic and new services data files and fixed components
  src/components/userComponents/basicInfoInput.jsx
  src/components/userComponents/eligible4Input.jsx
  src/components/userComponents/eligibleCardBoolInput.jsx
  src/components/userComponents/eligiblePagination.jsx
  src/components/userComponents/mainDetailsInput.jsx
  src/components/userComponents/speciallyWomenInput.jsx
  src/components/userComponents/yesNoButton.jsx
  src/data/eligibleData.js
  src/pages/user/eligible1.jsx
  src/pages/user/eligible2.jsx
  src/pages/user/eligible3.jsx
  src/pages/user/eligible4.jsx
  src/pages/user/minHeightTextarea.jsx
  src/service/eligibleService.js
Labels: documentation

#39 Loader component done
  src/App.jsx
  src/assets/logo.png
  src/components/loader.jsx
  src/main.jsx
Labels: enhancement

#40 404 page, view all couples page, add new couples, fixed footer not st…
  package.json
  public/locales/en/eligibleCouples.json
  public/locales/en/eligibleCouplesAdd.json
  public/locales/en/notFound.json
  public/locales/sin/notFound.json
  src/App.jsx
  src/assets/babycry.png
  src/components/footer.jsx
  src/index.css
  src/main.jsx
  src/pages/answer.jsx
  src/pages/drug.jsx
  src/pages/drugAdd.jsx
  src/pages/landing.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/edit.jsx
  src/pages/midwife/eligibleCouples/view.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/notFound.jsx
  src/theme.js
  yarn.lock
Labels: enhancement

#41 Get midwife by users area details section done
  src/data/mohData.js
  src/pages/user/dashboard.jsx
  src/service/answerService.js
  src/service/userService.js
Labels: documentation

#42 View eligible
  public/locales/en/eligible1.json
  public/locales/en/eligible3.json
  public/locales/en/eligibleCouples.json
  public/locales/en/eligibleCouplesView.json
  src/App.jsx
  src/components/ui/pageHeading.jsx
  src/pages/doctor/clinic.jsx
  src/pages/doctor/clinicDates.jsx
  src/pages/doctor/clinicReports.jsx
  src/pages/doctor/viewClinics.jsx
  src/pages/drug.jsx
  src/pages/drugAdd.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/edit.jsx
  src/pages/midwife/eligibleCouples/view.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/midwife/parents/viewAll.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible3.jsx
Labels: enhancement

#45 Eligible all done
  src/App.jsx
  src/components/userComponents/eligible4Input.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible4.jsx
  src/pages/user/minHeightTextarea.jsx
  src/service/eligibleService.js
Labels: documentation

#46 Use title and page heading
  src/components/ui/pageHeading.jsx
  src/hooks/useTitle.js
  src/pages/blog/blog.jsx
  src/pages/doctor/clinic.jsx
  src/pages/drug.jsx
  src/pages/drugAdd.jsx
  src/pages/forum.jsx
  src/pages/landing.jsx
  src/pages/login.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/signup.jsx
  src/pages/user/dashboard.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible2.jsx
  src/pages/user/eligible3.jsx
  src/pages/user/eligible4.jsx
  src/pages/user/growth.jsx
  yarn.lock
Labels: documentation

#47 Manage users data visualizing done
  src/App.jsx
  src/pages/manageusers.jsx
  src/pages/notFound.jsx
  src/service/userService.js
Labels: documentation

#48 Eligible missed page added and role base accessibility
  src/App.jsx
  src/components/logoutDialog.jsx
  src/components/navbar.jsx
  src/components/ui/heading.jsx
  src/components/userComponents/eligible4Input.jsx
  src/components/userComponents/minHeightTextarea.jsx
  src/data/eligibleData.js
  src/pages/doctor/clinic.jsx
  src/pages/doctor/clinicDates.jsx
  src/pages/doctor/clinicReports.jsx
  src/pages/doctor/viewClinics.jsx
  src/pages/drug.jsx
  src/pages/drugAdd.jsx
  src/pages/manageusers.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/view.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/midwife/parents/viewAll.jsx
  src/pages/notFound.jsx
  src/pages/user/dashboard.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible2.jsx
  src/pages/user/eligible3.jsx
  src/pages/user/eligible4.jsx
  src/pages/user/eligible5.jsx
  src/pages/user/growth.jsx
  src/service/eligibleService.js
  tailwind.config.js
Labels: documentation

#49 Remove errors toast and added role constant
  src/App.jsx
  src/components/navbar.jsx
  src/data/roleData.js
  src/pages/answer.jsx
  src/pages/drug.jsx
  src/pages/drugAdd.jsx
  src/pages/forum.jsx
  src/pages/login.jsx
  src/pages/manageusers.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/question.jsx
  src/pages/signup.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible4.jsx
Labels: documentation

#50 Fixed nav role not import bug
  src/App.jsx
  src/components/navbar.jsx
  src/service/userService.js
Labels: documentation

#51 Customize footer base on role
  src/components/footer.jsx
Labels: documentation

#52 Eligible user view and edit pages and empty error handled
  src/App.jsx
  src/pages/answer.jsx
  src/pages/drug.jsx
  src/pages/drugAdd.jsx
  src/pages/forum.jsx
  src/pages/login.jsx
  src/pages/manageusers.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/question.jsx
  src/pages/signup.jsx
  src/pages/user/eligible4.jsx
  src/service/eligibleService.js
Labels: documentation

#53 Eligible popup and userService to AuthService
  src/App.jsx
  src/components/eligiblePopup.jsx
  src/components/navbar.jsx
  src/components/ui/popup.jsx
  src/context/userAuth.jsx
  src/pages/login.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/signup.jsx
  src/service/authService.js
  src/service/userService.js
Labels: documentation

#55 midwife dashboard, calendar colors, eligible form styles
  src/App.jsx
  src/components/DateCalendarServerRequest.jsx
  src/pages/doctor/clinicReports.jsx
  src/pages/midwife/dashboard.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/theme.js
  tailwind.config.js
Labels: enhancement

#59 Add clinic and related components
  src/App.jsx
  src/components/Calendar.jsx
  src/components/eligiblePopup.jsx
  src/components/userComponents/MultipleSelectChip.jsx
  src/components/userComponents/contactMidwifeSection.jsx
  src/components/userComponents/getRegion.jsx
  src/pages/doctor/addClinic.jsx
  src/pages/midwife/dashboard.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/user/dashboard.jsx
  src/service/clinicService.js
Labels: documentation

#60 Login styles
  package.json
  src/App.jsx
  src/components/Calendar.jsx
  src/components/ClinicAddPopup.jsx
  src/components/StripedDataGrid.js
  src/components/eligiblePopup.jsx
  src/components/footer.jsx
  src/components/logoutDialog.jsx
  src/components/navbar.jsx
  src/components/ui/button.jsx
  src/components/ui/heading.jsx
  src/components/ui/item.jsx
  src/components/userComponents/MultipleSelectChip.jsx
  src/components/userComponents/contactMidwifeSection.jsx
  src/components/userComponents/eligible4Input.jsx
  src/components/userComponents/getRegion.jsx
  src/components/userComponents/wrapperCard.jsx
  src/context/userAuth.jsx
  src/index.css
  src/main.jsx
  src/pages/answer.jsx
  src/pages/doctor/addClinic.jsx
  src/pages/doctor/clinic.jsx
  src/pages/doctor/clinicReports.jsx
  src/pages/drug.jsx
  src/pages/drugAdd.jsx
  src/pages/forum.jsx
  src/pages/landing.jsx
  src/pages/login.jsx
  src/pages/manageClinics.jsx
  src/pages/manageusers.jsx
  src/pages/midwife/dashboard.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/view.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/question.jsx
  src/pages/signup.jsx
  src/pages/user/dashboard.jsx
  src/pages/user/eligible4.jsx
  src/service/authService.js
  src/service/clinicService.js
  src/service/eligibleService.js
  src/service/forumService.js
  src/service/userService.js
  src/theme.js
  tailwind.config.js
  yarn.lock
Labels: documentation

#61 Component wrong import bug fixed
  src/pages/manageClinics.jsx
  src/pages/memories.jsx
Labels: documentation

#65 Pregnancy page 1 done
  src/App.jsx
  src/components/navbar.jsx
  src/components/userComponents/basicInfoInput.jsx
  src/components/userComponents/customPagination.jsx
  src/data/eligibleData.js
  src/data/pregnancyData.js
  src/pages/pregnancycard/pregnancy1.jsx
  src/pages/pregnancycard/pregnancy2.jsx
  src/pages/pregnancycard/pregnancy3.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible2.jsx
  src/pages/user/eligible3.jsx
  src/pages/user/eligible4.jsx
  src/pages/user/eligible5.jsx
Labels: documentation

#67 Divisions
  src/App.jsx
  src/assets/mapMOH.png
  src/components/ClinicAddPopup.jsx
  src/components/RegionsAddPopup.jsx
  src/components/Search.jsx
  src/components/StripedDataGrid.js
  src/components/TableSearch.jsx
  src/pages/admin/manageClinics.jsx
  src/pages/admin/manageRegions.jsx
  src/pages/admin/manageusers.jsx
  src/pages/doctor/clinic.jsx
Labels: enhancement

#68 Pregnancy card
  src/App.jsx
  src/components/navbar.jsx
  src/components/userComponents/basicInfoInput.jsx
  src/components/userComponents/customPagination.jsx
  src/components/userComponents/dateInput.jsx
  src/components/userComponents/doubleInput.jsx
  src/components/userComponents/singleInput.jsx
  src/data/eligibleData.js
  src/data/pregnancyData.js
  src/pages/pregnancycard/pregnancy1.jsx
  src/pages/pregnancycard/pregnancy2.jsx
  src/pages/pregnancycard/pregnancy3.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible2.jsx
  src/pages/user/eligible3.jsx
  src/pages/user/eligible4.jsx
  src/pages/user/eligible5.jsx
Labels: documentation

#72 Colour Changes
  src/components/footer.jsx
  src/components/ui/badge.jsx
  src/pages/blog/blog.jsx
  tailwind.config.js
Labels: CSS Fixings

#76 doctor dashboard
  public/locales/en/login.json
  public/locales/en/signup.json
  src/App.jsx
  src/assets/doctor/clinic.png
  src/assets/doctor/drugs.png
  src/assets/doctor/patient.png
  src/components/navbar.jsx
  src/components/ui/calendar.jsx
  src/components/userComponents/contactMidwifeSection.jsx
  src/context/darkModeContext.jsx
  src/main.jsx
  src/pages/doctor/dashboard.jsx
  src/pages/midwife/dashboard.jsx
  src/pages/signup.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible2.jsx
  src/pages/user/eligible3.jsx
  src/pages/user/eligible4.jsx
  src/pages/user/growth.jsx
  yarn.lock
Labels: documentation

#77 Nav
  public/locales/en/manageClinics.json
  src/App.jsx
  src/components/ClinicAddPopup.jsx
  src/components/nav.jsx
  src/data/navConfig.js
  src/pages/admin/addClinic.jsx
  src/pages/admin/manageClinics.jsx
  src/service/clinicService.js
Labels: documentation

#78 App runtime error fixed
  src/App.jsx
  src/components/nav.jsx
  src/context/darkModeContext.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/user/growth.jsx
  yarn.lock
Labels: documentation

#79 Vaccinecard - Parent View
  src/App.jsx
  src/assets/user/clinic.png
  src/assets/user/dashboardImage-eligible.png
  src/pages/vaccinecard/vaccinecard.jsx
Labels: enhancement

#81 Nav config to config
  src/App.jsx
  src/components/navbar.jsx
  src/config/navConfig.js
Labels: documentation

#82 Question
  src/App.jsx
  src/pages/admin/adminDashboard.jsx
  src/pages/admin/manageBlogs.jsx
  src/pages/answer.jsx
  src/pages/editQuestion.jsx
  src/pages/question.jsx
Labels: bug

#83 Clinic add done
  src/App.jsx
  src/components/ClinicAddPopup.jsx
  src/components/nav.jsx
  src/components/userComponents/MultipleSelectChip.jsx
  src/pages/admin/addClinic.jsx
Labels: documentation

#84 add clinic popup style fix
  src/components/ClinicAddPopup.jsx
  src/components/userComponents/MultipleSelectChip.jsx
  src/pages/login.jsx
Labels: CSS Fixings

#85 Merge Blog Get and Post functionality with Dev branch
  package.json
  src/App.jsx
  src/components/blogComponents/BlogProgress.jsx
  src/components/blogComponents/blogHeading.jsx
  src/pages/blog/blog.jsx
  src/pages/blog/writeblog1.jsx
  src/pages/blog/writeblog2.jsx
  src/pages/blog/writeblog3.jsx
  src/pages/blog/writeblog4.jsx
  src/service/blogService.js
  yarn.lock
Labels: functionality implemented

#87 Added the blog article data
  src/pages/blog/article.jsx
  src/pages/blog/blog.jsx
Labels: enhancement

#88 added parents view page and popup
  src/App.jsx
  src/components/parentPopup.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/midwife/parents/viewAll.jsx
Labels: enhancement

#89 Presentation changes and view clinics
  src/App.jsx
  src/components/ClinicAddPopup.jsx
  src/components/eligiblePopup.jsx
  src/components/nav.jsx
  src/components/userComponents/contactMidwifeSection.jsx
  src/components/userComponents/doubleInput.jsx
  src/config/navConfig.js
  src/pages/admin/adminDashboard.jsx
  src/pages/admin/manageClinics.jsx
  src/pages/answer.jsx
  src/pages/blog/blog.jsx
  src/pages/forum.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/pregnancycard/pregnancy1.jsx
  src/pages/pregnancycard/pregnancy2.jsx
  src/pages/pregnancycard/pregnancy3.jsx
  src/pages/user/eligible1.jsx
  src/pages/user/eligible2.jsx
  src/pages/user/eligible3.jsx
  src/pages/user/eligible4.jsx
  src/pages/user/eligible5.jsx
  src/service/clinicService.js
  src/service/userService.js
Labels: documentation

#90 midwife
  src/App.jsx
  src/pages/doctor/midwife.jsx
Labels: enhancement

#91 Month calendar view
  src/components/ClinicAddPopup.jsx
  src/components/ui/calendar.jsx
  src/pages/admin/manageClinics.jsx
  src/service/clinicService.js
Labels: enhancement

#93 Update role for parent and parents
  src/components/customDialog.jsx
  src/components/nav.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/midwife/parents/viewAll.jsx
  src/service/eligibleService.js
Labels: documentation

#94 growth page excercies
  src/assets/user/yoga.png
  src/pages/midwife/dashboard.jsx
  src/pages/user/growth.jsx
Labels: enhancement
