Repository Maathru/Frontend-Web-, pull requests merged in 2024-11, with the labels that each got.

#121 Scroll
  package.json
  src/components/EligibleComponents/FamilyHealthDetails.jsx
  src/components/EligibleComponents/HealthDetails.jsx
  src/components/PregnancyComponents/MainDetails.jsx
  src/components/PregnancyComponents/PostnatalCare.jsx
  src/pages/pregnancycard/pregnancy.jsx
  src/pages/user/eligible.jsx
  yarn.lock
Labels: enhancement

#136 Employee registration done
  src/components/ScrollToTop.js
  src/components/ScrollToTop.jsx
  src/components/UserAddPopup.jsx
  src/pages/admin/manageusers.jsx
  src/service/employeeService.js
Labels: documentation

#137 Eligible user status change button bug fixed
  src/pages/midwife/eligibleCouples/add.jsx
Labels: documentation

#144 Bmi auto generation done
  src/pages/midwife/eligibleCouples/add.jsx
Labels: enhancement

#145 Eligible user deletion done
  src/components/deleteConfirmationDialog.jsx
  src/pages/admin/manageRegions.jsx
  src/pages/answer.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/service/eligibleService.js
Labels: documentation

#146 Fixed build errors
  src/components/UserAddPopup.jsx
Labels: documentation

#151 minor style changes
  src/pages/doctor/clinic.jsx
  src/pages/doctor/dashboard.jsx
  src/pages/forum.jsx
  src/pages/memories.jsx
  src/pages/midwife/dashboard.jsx
  src/pages/midwife/parents/viewAll.jsx
  src/pages/user/dashboard.jsx
Labels: CSS Fixings

#152 127 midwife dashboard clinics section
  src/components/midwifeComponents/ClinicViewSection.jsx
  src/pages/admin/manageClinics.jsx
  src/pages/doctor/dashboard.jsx
  src/pages/midwife/dashboard.jsx
  src/service/clinicService.js
  src/utils/FormatTime.js
Labels: enhancement

#153 Contact midwife bug fixed resolve #148
  src/components/userComponents/getRegion.jsx
Labels: documentation

#154 fixed #150
  src/App.jsx
  src/pages/doctor/clinic.jsx
  src/pages/doctor/clinicDates.jsx
  src/pages/doctor/viewClinics.jsx
Labels: enhancement

#155 Fetch pregnancy card data for parent up to child birth
  src/components/PregnancyComponents/AddRecordForm.jsx
  src/components/PregnancyComponents/ChildBirth.jsx
  src/components/PregnancyComponents/ClinicalConservation.jsx
  src/components/PregnancyComponents/CurrentPregnancyStatus.jsx
  src/components/PregnancyComponents/FamilyHistoryDetails.jsx
  src/components/PregnancyComponents/ParentsDetails.jsx
  src/components/PregnancyComponents/PregnancyHistory.jsx
  src/data/pregnancyData.js
  src/pages/pregnancycard/pregnancy.jsx
  src/service/pregnancyService.js
Labels: enhancement, functionality implemented

#156 Doctor clinic page data loading
  src/pages/admin/manageClinics.jsx
  src/pages/doctor/clinic.jsx
  src/service/clinicService.js
Labels: enhancement

#157 resolve #122
  src/components/eligiblePopup.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
Labels: documentation

#162 128 individual home visit page
  src/App.jsx
  src/pages/midwife/homeVisit.jsx
  src/pages/midwife/parents/viewAll.jsx
  src/service/employeeService.js
Labels: documentation

#163 Fix some addtional issues
  src/pages/midwife/homeVisit.jsx
  src/service/employeeService.js
Labels: enhancement

#164 dynamic growthdata
  src/data/growthData.js
  src/pages/user/growth.jsx
Labels: functionality implemented

#167 Fixes
  src/components/pagination-dynamic.jsx
  src/pages/forum.jsx
  src/pages/user/growth.jsx
  src/service/forumService.js
  src/service/growthService.js
Labels: enhancement, CSS Fixings

#172 Image upload
  src/components/ImageUpload.jsx
  src/service/ImageService.js
Labels: enhancement

#176 Answer fixes
  src/pages/answer.jsx
Labels: bug
