Repository Maathru/Frontend-Web-, pull requests merged in 2024-12, with the labels that each got.

#179 Chat done
  index.html
  src/App.jsx
  src/assets/user_icon.png
  src/config/navConfig.js
  src/pages/Chat.jsx
  vite.config.js
  yarn.lock
Labels: enhancement

#181 fixed clinic page toggle content
  src/App.jsx
  src/components/eligiblePopup.jsx
  src/components/parentPopup.jsx
  src/components/userComponents/ParentClincsSection.jsx
  src/pages/admin/manageClinics.jsx
  src/pages/doctor/clinic.jsx
  src/pages/doctor/dashboard.jsx
  src/pages/midwife/clinics/Clinics.jsx
  src/pages/midwife/clinics/HomeVisits.jsx
  src/pages/midwife/clinics/mohClinics.jsx
  src/pages/midwife/dashboard.jsx
  src/pages/midwife/eligibleCouples/viewAll.jsx
  src/pages/midwife/parents/viewAll.jsx
  src/service/clinicService.js
Labels: enhancement

#185 Drug page to doctor
  src/App.jsx
  src/config/navConfig.js
  src/pages/admin/manageDrugs.jsx
Labels: documentation

#186 Growth fixes
  src/App.jsx
  src/data/growthData.js
  src/pages/doctor/dashboard.jsx
  src/pages/doctor/medicalRecords.jsx
  src/pages/user/growth.jsx
  src/service/medicalRecordService.js
Labels: bug

#188 add home visit, chat styles
  src/App.jsx
  src/components/midwifeComponents/HomeVisitDates.jsx
  src/index.css
  src/pages/Chat.jsx
  src/pages/midwife/clinics/HomeVisits.jsx
  src/pages/midwife/clinics/mohClinics.jsx
  src/pages/midwife/eligibleCouples/add.jsx
  src/pages/pregnancycard/pregnancy.jsx
Labels: enhancement, CSS Fixings

#184 Profile
  src/App.jsx
  src/pages/admin/manageusers.jsx
  src/pages/profile.jsx
  src/service/userService.js
Labels: documentation, enhancement, functionality implemented

#190 Hide footer for chat
  src/App.jsx
  src/components/nav.jsx
  src/config/navConfig.js
  src/data/roleData.js
  src/pages/login.jsx
  src/service/authService.js
Labels: documentation, enhancement

#193 minor style changes
  src/components/ui/button.jsx
  src/index.css
  src/pages/Chat.jsx
  src/pages/midwife/clinics/mohClinics.jsx
  src/pages/profile.jsx
Labels: CSS Fixings

#196 Home visits add section
  src/components/midwifeComponents/HomeVisitDates.jsx
  src/pages/pregnancycard/pregnancy.jsx
  src/service/clinicService.js
Labels: documentation

#197 Flow fixes
  src/components/PregnancyComponents/HealthDetails.jsx
  src/components/analyticComponents/BirthsByMonths.jsx
  src/components/analyticComponents/PregnancyAnalysisByRegion.jsx
  src/components/analyticComponents/PregnancyCountByAge.jsx
  src/components/analyticComponents/diseaseAnalysis.jsx
  src/pages/answer.jsx
  src/pages/landing.jsx
  src/pages/user/dashboard.jsx
Labels: bug

#199 Home visits for midwife
  src/components/midwifeComponents/HomeVisitDates.jsx
  src/pages/midwife/clinics/HomeVisits.jsx
  src/pages/midwife/clinics/mohClinics.jsx
  src/service/visitsService.js
Labels: functionality implemented

#203 Home visits for parent
  src/components/userComponents/ParentClincsSection.jsx
  src/pages/user/growth.jsx
  src/service/visitsService.js
Labels: functionality implemented

#204 Fix/popup
  src/components/map/LocationAddPopup.jsx
  src/components/midwifeComponents/HomeVisitDates.jsx
  src/config/navConfig.js
  src/index.css
  src/pages/admin/manageRegions.jsx
  src/pages/blog/writeblog1.jsx
  src/pages/landing.jsx
Labels: enhancement, CSS Fixings

#205 Home visit page for midwife
  src/pages/midwife/clinics/HomeVisits.jsx
  src/pages/midwife/homeVisit.jsx
Labels: documentation, functionality implemented

#207 logs line by line
  src/pages/admin/logs.jsx
Labels: enhancement
